name: Fluctux backend Docker image CI & CD

on:
  push:
    branches:
      - main
    paths:
      - 'server.ts'
  
jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker build -t dockermahin/fluctux-backend:2.3.1 .

      - name: Push to Docker Hub
        run: |
          docker login -u dockermahin -p ${{ secrets.DOCKER_PASSWORD }}
          docker push dockermahin/fluctux-backend:2.3.1
