name: Test

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker build -t dockermahin/fluctux-backend:2.3.1 .
